language: ruby
cache:
  - bundler
  - pip
rvm:
  - 2.3
jdk:
  - oraclejdk8
before_script:
  - pip install --user html5validator
script: ./travis/script/cibuild
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: script
  script: ./travis/script/deploy
  skip_cleanup: true
  on:
    branch: master
