#!/bin/bash

ln -s ./jekyll-site-sd/.travis.yml
ln -s ./jekyll-site-sd/_config.yml
ln -s ./jekyll-site-sd/Gemfile

if [[ ! -e .travis ]]; do
  mkdir .travis
  cp -r ./jekyll-site-sd/travis/* .travis
fi

if [[ ! -e .gitignore ]]; do
  cp ./jeyll-site-sd/.gitignore .
fi

if [[ ! -e env ]]; do
  cp ./jeyll-site-sd/env .
fi
